name: Test validation
on:
#  # Uncomment when test added first time to register workflow and comment it back after workflow would be registered
#  #
#  # Added pull_request to register workflow from the PR.
#  # Read more https://stackoverflow.com/questions/63362126/github-actions-how-to-run-a-workflow-created-on-a-non-master-branch-from-the-wo
#  pull_request: {}
  workflow_dispatch: {}

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: echo "Do setup"

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ["one", "two"]
    continue-on-error: true
    needs: [setup]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./
        id: current
        with:
          matrix-step-name: ${{ github.job }}
          matrix-key: ${{ matrix.target }}
          outputs: |-
            result: ${{ matrix.target }}
            test: comment: URL for deploy: https://frontend-docs-259.website.dev

      - uses: nick-fields/assert-action@v2
        with:
          expected: ${{ matrix.target }}
          actual: ${{ fromJson(steps.writer.outputs.result).result }}

      - uses: nick-fields/assert-action@v2
        with:
          expected: "comment: URL for deploy: https://frontend-docs-259.website.dev"
          actual: ${{ fromJson(steps.writer.outputs.result).test }}

    outputs:
      result: "${{ steps.current.outcome }}"

  assert:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: nick-fields/assert-action@v2
        with:
          expected: 'failure'
          actual: "${{ needs.test.outputs.result }}"


  teardown:
    runs-on: ubuntu-latest
    needs: [assert]
    if: ${{ always() }}
    steps:
      - name: Tear down
        run: echo "Do Tear down"
